name: Github Actions Demo

on:
  push:
    branches:
      - main # filter

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello step
        run: echo "The job was triggered by a ${{ github.event_name }} event."
      - name: run python step
        run: |
          pip install -r requirements.txt
          python3 ci.py
