name: Github Secret Demo

on: push

jobs:
  secrets-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          import os
          print(len(os.getenv('MY_VAR')))
        shell: python
    env:
      MY_VAR: ${{ secrets.MY_SECRET }}
